---
- name: Ensure NFS utilities are installed.
  package: name=nfs-utils state=present

- name: Ensure rpcbind is running as configured.
  service:
    name: rpcbind
    state: "{{ nfs_rpcbind_state }}"
    enabled: "{{ nfs_rpcbind_enabled }}"

- name: Enable nfsidmap if enabled
  become: True
  shell: "echo N > /sys/module/nfsd/parameters/nfs4_disable_idmapping"
  when: nfs_idmap_enable == True